version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
    labels:
      - "maven"
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/software/demofunction"
    schedule:
      interval: "daily"
    labels:
      - "maven"
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/software/configvalidator"
    schedule:
      interval: "daily"
    labels:
      - "maven"
      - "dependencies"
