name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        java: [11.0.x]
    name: Java ${{ matrix.java }}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Infrastructure Maven
        run: |
          cd ./infrastructure
          mvn -B package --file pom.xml
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Updload artifact
        with:
          name: pr
          path: pr/